language: c
compiler:
  - clang
  - gcc

env:
  - DEBUG=0
  - DEBUG=1

# needed for libuv
before_install:
  - git submodule update --init --recursive
install:
  - sudo apt-get update -qq
#  - sudo apt-get install -qq libdisasm-dev

script: make config CC=$CC DEBUG=$DEBUG; make && make test

notifications:
  irc: "irc.perl.org#perl11"
