language: c
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
install:
  - sudo apt-get install -qq libdisasm-dev

script: make config; make && make test CC=$CC

notifications:
  irc: "irc.perl.org#perl11"
