language: c
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
#install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq libdisasm-dev
script: make config CC=$CC; make && make test
notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: change
    on_failure: change
