language: c
compiler:
  - gcc
  - clang
before_install:
  - git submodule update --init --recursive
#install:
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq libdisasm-dev

script: make config CC=$CC; make && make test

notifications:
  irc: "irc.perl.org#perl11"
