language: c
compiler:
  - gcc
  - clang
  - g++
before_install:
  - git submodule update --init --recursive
install: echo
script: make config; make && make test CC=$CC
notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: change
    on_failure: change
